### PR TITLE
Create TERMS.md

### PR DESCRIPTION
**Pull request by jijordre**

### CODE REVIEW

**Review by morfj — CHANGES_REQUESTED** [review]
Needs a version bump in the package.json file

**Comment by jijordre** [comment]
Pre-release version got incremented.

**Comment by morfj** [comment]
Should we also bump the dependency to the SDK so its using the SDK with the same terms?

**Comment by jijordre** [comment]
Dependency on _nahmii-sdk_ was updated to 1.0.0-beta.34.

**Review by morfj — APPROVED** [review]

**Pull request merged**
